### ISSUE TITLE
Reconnect logic not working with error 1006

### ISSUE THREAD

**Issue by eulphean** [web3data/web3data-js#31]
Reconnect logic doesn't execute when the websocket gets disconnected due to error 1006. It just gets stuck at Attempting to Reconnect... and it never reconnects. Attached is a screenshot. 

![Screen Shot 2019-10-02 at 1 36 25 PM](https://user-images.githubusercontent.com/4178424/66134387-e1b7a780-e5bd-11e9-9255-63d6e9f1ab03.png)

**Comment by taylorjdawson** [comment]
Thanks for the feedback! I'll take a look and get back to you.

**Comment by taylorjdawson** [comment]
@eulphean Let me know if you have anymore issues but this one should be resolved. Thanks again!
